os: linux
dist: focal
language: generic
services:
  - docker

env:
  # It seems that for docker-compose to be able to use a git url as context
  # one needs to upgrade to version 2, refer to this issue
  #    https://github.com/docker/compose/issues/8309#issuecomment-1400206290
  # With docker-compose version 1.29.2 one gets the following error message
  #    unable to 'git clone' to temporary context directory: 
  #    error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEIXgF97G/libcrypto.so.1.1: 
  #    version `OPENSSL_1_1_1' not found
  - DOCKER_COMPOSE_VERSION=v2.16.0
  
before_install:
  # Upgrading docker-compose, refer to
  #    https://docs.travis-ci.com/user/docker/?#using-docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose --version

jobs:
  include:
    - stage: Building and running imuv container
      script:
        - cp env-default .env
        - mkdir wbo-boards
        - sudo chown -R 1000:1000 wbo-boards
        - docker-compose build
        - docker-compose up -d
        # - curl -X POST -H "X-Parse-Application-Id: my_parse_app_id" -H "Content-Type: application/json" -d '{"score":1337,"playerName":"John Doe","cheatMode":false}' http://localhost:1337/parse/classes/GameScore
        # - curl -X GET -H "X-Parse-Application-Id: my_parse_app_id" http://localhost:1337/parse/classes/GameScore/8A0YN6GkJ7
        - travis_wait 2
        - docker-compose down
