version: "3.3"

services:
  mongodb:
    # Warning: version 5.0.1 requires so called AVX support, refer to
    # https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
    # https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
    image: mongo:4.4.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - mynetwork

  parse-server:
    image: parseplatform/parse-server:7.0.0
    restart: always
    ports:
      - ${PARSE_PORT}:1337
    depends_on:
      - "mongodb"
    command: --appId ${PARSE_APP_ID} --masterKey ${PARSE_MASTER_KEY} --databaseURI mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT} --masterKeyIps ${PARSE_MASTER_KEY_IPS}
    networks:
      - mynetwork

  wbo:
    image: lovasoa/wbo
    restart: always
    ports:
      - ${WBO_PORT}:80
    volumes:
      - ./wbo-boards:/opt/app/server-data
    networks:
      - mynetwork

  # At some point the demo will also need the following service
  imuv:
    build:
      context: https://github.com/VCityTeam/UD-Imuv-docker.git
      dockerfile: Context/Dockerfile
      args:
        - checkoutName=main #branch or sha of commit
    ports:
      - ${IMUV_PORT}:8000
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: ${PARSE_MASTER_KEY_IPS}
        - subnet: "2001:3984:3989::/64"
    driver_opts:
      com.docker.network.bridge.name: br-imuv
    # Refer to
    #   https://github.com/VCityTeam/UD-Imuv-docker/blob/master/Readme.md
    # but some env.json will be needed and for this the imuv application
    # will need to be changed to accept it's configuration at launch time
    # as opposed to (docker) build time.
    # Additionnaly this env.json configuration file will need to integrate
    # the above parse-server parameters PARSE_APP_ID, PARSE_MASTER_KEY
    # as well as PARSE_PORT. For this either a file template generator will
    # be needed or imuv (docker container) will need to accept further CLI
    # arguments (the later probably being the hardest way to do it).
